# Optional: use if the Cloud Run trigger runs this file (not the default GitHub pack step).
steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - $_IMAGE_NAME
      - --builder=gcr.io/buildpacks/builder:latest
      - --path=.
      - --env=GOOGLE_PYTHON_VERSION=3.11.x
images:
  - $_IMAGE_NAME
